[package]
name = "rapl"
version = "0.4.0"
edition = "2021"
rust-version = "1.82"
description = "A crate that makes numerical scripting with Rust simple and enjoyable."
readme = "README.md"
repository = "https://github.com/JErnestoMtz/rapl"
license = "MIT"
keywords = ["array", "ndarray", "tensor", "apl", "math"]
categories = ["mathematics", "science"]
exclude = ["graphics/"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
num-traits = "0.2.15"
typenum = "1.16.0"
generic-array = "1.4"

[features]
default = ["complex"]
fft = ["complex"]
complex = []

[dev-dependencies]
image = "0.24.6"

[[example]]
name = "image_fft"
required-features = ["fft"]
